### ISSUE TITLE
StreamSyncedMetaData has been broken by dev.303 or 304

### ISSUE THREAD

**Issue by M1raclee** [altmp/coreclr-module#7]
It seems like something happened with key names. I saw some changes in http_client.cpp in 89b8ad3cf125547e94cf22603535383e192e457a, maybe it's a reason, because yesterday same code worked fine

In most cases keys looks like "empty":
![image](https://github.com/altmp/coreclr-module/assets/49681421/0ed48bc8-38b1-46c2-afb2-16aa851257ef)

And sometimes it has strange symbols instead key name:
![image](https://github.com/altmp/coreclr-module/assets/49681421/d6088242-e663-47db-a7e6-d1a711c1653f)

Server-side:
```
Alt.OnPlayerConnect += (player, _) =>
{
     player.SetStreamSyncedMetaData("TestUserKey", "test user string data");
};
```

Client-side:

```
Alt.OnStreamSyncedMetaChange += (entity, key, newValue, oldValue) =>
{
    Alt.Log($"StreamSyncedMetaChange: {entity.Type}, {entity.Id}, Key: {key}, old: {oldValue}, new: {newValue}");
};

await Task.Delay(3000);

Alt.LocalPlayer.GetStreamSyncedMetaData("TestUserKey", out var value);
Alt.Log("StreamSyncedMetaData with key 'TestUserKey': " + value);
```

Expected result:
Get a set value when request a meta-data by key

Actual result:
Get an "empty" value, because key name is broken (see StreamSyncedMetaChange)

It worked fine for dev.299, but broken with dev.304 (client-side)

**Comment by xLuxy** [comment]
Same thing also happens on JS using the following code:

### Client:
```js
alt.on('streamSyncedMetaChange', alt.log);
```

### Server:
```js
player.setStreamSyncedMeta('hello', 'there');
player.setStreamSyncedMeta('hello', 'yes');
```

**Comment by M1raclee** [comment]
Fixed in [dev.306](https://github.com/altmp/coreclr-module-runtime/commit/b5148cc9e593eb99f9c31de84977df726c16afe6)
